### ISSUE TITLE
Funkcionalnosti u vezi zbirke kratkih pitanja

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#19]
Ovo sam ostavio u formi kako je Ana navela, a može da se vidi kako najbolje da se odgovori na te potrebe:

1. Nedostaje ceo deo vezan za karel robota. Za njega nam je potrebno da bude omogućeno *ubacivanje slike u postavku zadatka*.
2. *Višestruki tačni odgovori* nisu omogućeni. Taj problem je bio prevaziđen tako što je traženo da ponuđeni odgovori budu sortirani i spojeni u jednu reč, npr. 235.
3. Valjalo bi da kod bude formatiran malo manjim fontom. Čini mi se upadljivo većim u odnosu na običan tekst - *ovo verovatno nije problem sa samim fontom, već kako je tekst protumačen*
![grananje](https://user-images.githubusercontent.com/10418572/41745778-6ace9074-75a8-11e8-823c-88777ac3e325.png)
4. Postoje pitanja u kojima bi bilo idealno da đak sam napiše liniju koda koja nedostaje. Za proveru ispravnosti nemamo podršku. Ima li smisla komplikovati - *ovo ćemo razmisliti, može se iskomunicirati sa Anom dodatno ako treba*

**Comment by denkoRa** [comment]
` .. code-block:: python

    l = [90, 49, 45, 8, 66, 88]  
    parni = True

    for x in l:
    if (x % 2 != 0):          
      parni = False
    print(parni)`

**Comment by denkoRa** [comment]
Visestruki odgovori su dodati. Implementiraju se tako sto se u yaml fajlu odgovor zabelezi na sledeci nacin:
```
odgovor:     
      - oznaka: "а"
      - oznaka: "г"
````
Ovo je u slucaju da su odgovori pod **а** i **г** tacni. 
U slucaju da je samo 1 odgovor tacan, ostaje isto kao do sada 
`
odgovor: "a"
`

**Comment by denkoRa** [comment]
Sto se tice ubacivanja slika u zadatak, najlaksi nacin je pomocu direktive.

```.. image:: path_to_image```

Npr.
```.. image:: ../../../images/bunny.jpg```

**Comment by anakapmal** [comment]
Što se višestrukih odgovora tiče, nešto ne izvodim kako treba. 
U izraze, pitanje 3, sam dodala da su i a i b tačni odgovori, ali su mi dugmići za čekiranje i dalje tipa radio button-a i ne dozvoljavaju višestruku selekciju.
Da li je dovoljno da pitanje formulišem ovako:
```
  - tip: abc
    id: dva_izraza_veci
    nivo: 2
    tekst: |
      Пајтон окружење ће исписати већи број када израчуна вредност којег од наредна два израза?
    opcije:
      - oznaka: "а"
        tekst: |
          ``({b1} + {b2}) * {cinilac} + {b3}``
      - oznaka: "б"
        tekst: |
          ``{b1} + {b2} * {cinilac} + {b3}``
    odgovor:     
      - oznaka: "а"
      - oznaka: "б"
```
ili sam nešto propustila?
