### ISSUE TITLE
UX-a u dashbordu u vezi Zbirke kratkih pitanja - dorade 2

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#20]
Ostalo je još part detalja da se upegla:
* Kada se edituje test, onda se u formi koja se otvori ne popune check boksovi i kontrole za broj pitanja po nivoima
* Kada se kreira nov test treba da se za kombinaciju stavi 0, a za postojeće ne bi bilo loše da se u napravi upit u bazu da se unesu nule gde je NULL. ovo je detalj, pretpostavljam da NULL daje isto što i nula, ali mi se čini manje složeno za razumevanje da šifra uvek bude broj.
* Kod ponuđenih odgovora  staviti da je slovna oznaka odgovora u posebnoj koloni (td-u), tj.   
umesto  `<td><b>a)</b>&nbsp;... </td>` da stoji `<td><b>a)</b></td><td> ... </td>` 
* Treba malo popraviti razmake, dodaj pravila za stil:   
```css
.question p {
    margin-top: 0.5em;
}

.question blockquote {
     margin-bottom: 0;
}
```
