### ISSUE TITLE
Mala dorada na issue #20

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/RunestoneExtensions#23]
U vezi issue #20, umesto:
```css
        .question p {
            margin-top: 0.5em;
        }
```
treba da stoji (da bi bile poravnate slovne oznake i tekst nakon njih):

```css
        .question p {
            margin-bottom: 0.5em;
        }
```
